### ISSUE TITLE
(🎁) Check usages as well as imports

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/pylint-module-boundaries#15]
if `foo.bar` is banned, then the following shouldn't be allowed:
```py
import foo

foo.bar.baz("")
```

**Comment by DetachHead** [comment]
this is a tough one because in many cases you'd have the same error reported twice, which i think would be annoying
```py
from foo import bar # pylint:disable=banned-imports

bar.baz("") # error here still
```

this is still preferable to them not being checked at all though so i'll do it

**Comment by KotlinIsland** [comment]
> this is a tough one because in many cases you'd have the same error reported twice

That is literally nothing more that a minor inconvenience.

I can't imagine it would be that difficult to only report on usages that are a member expression. Such that `foo.bar` is reported against, but `bar` is not.

**Comment by DetachHead** [comment]
> That is literally nothing more that a minor inconvenience.

If I want to `eslint-disable` the import on a class for whatever reason, I don’t want to also have to put `eslint-disable` comments on every usage of any members of that class. I can imagine that being more than just a minor inconvenience
